"""Add queue_position column to visit table

Revision ID: 234e8c9d1e7f
Revises: 33610eb7d65e
Create Date: 2026-04-09 23:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '234e8c9d1e7f'
down_revision = '33610eb7d65e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('queue_position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_column('queue_position')
    # ### end Alembic commands ###
