"""empty message

Revision ID: 27b8c558c6a3
Revises: 
Create Date: 2026-04-11 17:06:25.713566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27b8c558c6a3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('phone_2'))

    with op.batch_alter_table('process', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'section', ['section_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('process', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('phone_2'), ['phone'], unique=False)

    # ### end Alembic commands ###
