"""empty message

Revision ID: 33610eb7d65e
Revises: 
Create Date: 2026-04-09 22:13:42.126915

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33610eb7d65e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('berth_date',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               nullable=False)
        batch_op.create_unique_constraint(None, ['national_id'])

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('berth_date',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               type_=sa.Date(),
               nullable=False)
        batch_op.alter_column('clinic_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'patient', ['patient_phone'], ['phone'])
        batch_op.create_foreign_key(None, 'patient', ['patient_name'], ['name'])
        batch_op.drop_column('process_cost')
        batch_op.drop_column('visit_date_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_date_login', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('process_cost', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('clinic_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('berth_date',
               existing_type=sa.Date(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               nullable=True)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               nullable=True)
        batch_op.alter_column('berth_date',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               existing_nullable=True)

    # ### end Alembic commands ###
