"""add consultation fields

Revision ID: 6d18b0ee7abc
Revises: 
Create Date: 2026-04-09 19:36:59.349148

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d18b0ee7abc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consultation_time', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_doctor_date'))
        batch_op.drop_constraint(batch_op.f('consultation_time_ibfk_3'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('consultation_time_ibfk_2'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('consultation_time_ibfk_4'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('consultation_time_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'clinics', ['clinic_id'], ['clinic_id'])
        batch_op.create_foreign_key(None, 'visit', ['previous_visit_id'], ['id'])
        batch_op.create_foreign_key(None, 'doctor', ['doctor_id'], ['id'])
        batch_op.create_foreign_key(None, 'visit', ['current_visit_id'], ['id'])
        batch_op.drop_column('created_at')

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.drop_index(batch_op.f('FK_sectionID'))
        batch_op.drop_index(batch_op.f('doctor_ibfk_1'))
        batch_op.create_foreign_key(None, 'section', ['section_id'], ['id'])
        batch_op.create_foreign_key(None, 'clinics', ['clinic_id'], ['clinic_id'])
        batch_op.drop_column('total_visits_month')
        batch_op.drop_column('total_visits_today')
        batch_op.drop_column('current_queue_position')

    with op.batch_alter_table('featurs', schema=None) as batch_op:
        batch_op.alter_column('code',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=80),
               type_=sa.String(length=70),
               existing_nullable=False)
        batch_op.alter_column('discreption',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=80),
               type_=sa.String(length=100),
               nullable=True)

    with op.batch_alter_table('featursplans', schema=None) as batch_op:
        batch_op.alter_column('plan_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('featur_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.alter_column('invoice_date',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('discount',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'غير مدفوع'"))
        batch_op.drop_column('remaining_amount')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('national_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=14),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('berth_date',
               existing_type=mysql.YEAR(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               nullable=False)
        batch_op.alter_column('section',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('normalized_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True)
        batch_op.drop_index(batch_op.f('fk_doctor_id'))
        batch_op.drop_index(batch_op.f('id_clinic'))
        batch_op.drop_index(batch_op.f('section_2'))
        batch_op.create_unique_constraint(None, ['national_id'])
        batch_op.create_foreign_key(None, 'clinics', ['clinic_id'], ['clinic_id'])
        batch_op.create_foreign_key(None, 'doctor', ['doctor_id'], ['id'])

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('invoice_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('payment_date',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.drop_constraint(batch_op.f('discount'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('patient_id'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('idprocess'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('cost_process'), type_='foreignkey')
        batch_op.drop_column('process_cost')
        batch_op.drop_column('payment_date_time')
        batch_op.drop_column('idprocess')
        batch_op.drop_column('discount')

    with op.batch_alter_table('percentages', schema=None) as batch_op:
        batch_op.alter_column('percentage',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.create_unique_constraint('_doctor_process_uc', ['doctor_id', 'process_id'])

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=25),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.drop_column('discreption')

    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.alter_column('discount',
               existing_type=mysql.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               type_=sa.String(length=50),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('date_performed',
               existing_type=mysql.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('fk_clinic_section'))
        batch_op.drop_index(batch_op.f('naem_section'))
        batch_op.create_foreign_key(None, 'clinics', ['clinic_id'], ['clinic_id'])
        batch_op.drop_column('doctors_name')
        batch_op.drop_column('doctor_id')

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.alter_column('normalized_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=True)
        batch_op.alter_column('berth_date',
               existing_type=mysql.YEAR(),
               type_=sa.Date(),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               nullable=False)
        batch_op.alter_column('national_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=14),
               type_=sa.Integer(),
               nullable=True)
        batch_op.alter_column('clinic_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('visit_date',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.alter_column('percentage',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('actual_start_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Timestamp when doctor clicked Next to START this visit',
               existing_nullable=True)
        batch_op.alter_column('actual_end_time',
               existing_type=mysql.DATETIME(),
               comment=None,
               existing_comment='Timestamp when doctor clicked Next to END this visit',
               existing_nullable=True)
        batch_op.alter_column('queue_status',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               type_=sa.String(length=50),
               nullable=True,
               comment=None,
               existing_comment='Dynamic queue state: waiting | in_progress | completed | paused',
               existing_server_default=sa.text("'waiting'"))
        batch_op.drop_index(batch_op.f('FK_age'))
        batch_op.drop_index(batch_op.f('FK_gender'))
        batch_op.drop_index(batch_op.f('idx_visit_clinic_id'))
        batch_op.drop_index(batch_op.f('national_id_FK'))
        batch_op.drop_index(batch_op.f('visit_ibfk_1'))
        batch_op.drop_index(batch_op.f('visit_ibfk_2'))
        batch_op.drop_index(batch_op.f('visit_ibfk_3'))
        batch_op.drop_constraint(batch_op.f('process_cost'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'doctor', ['doctor_id'], ['id'])
        batch_op.create_foreign_key(None, 'section', ['section_id'], ['id'])
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'patient', ['national_id'], ['national_id'])
        batch_op.create_foreign_key(None, 'patient', ['patient_phone'], ['phone'])
        batch_op.create_foreign_key(None, 'patient', ['status'], ['status'])
        batch_op.create_foreign_key(None, 'patient', ['patient_name'], ['name'])
        batch_op.create_foreign_key(None, 'clinics', ['clinic_id'], ['clinic_id'])
        batch_op.drop_column('process_cost')
        batch_op.drop_column('visit_date_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_date_login', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('process_cost', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('process_cost'), 'process', ['process_cost'], ['fee_process'])
        batch_op.create_index(batch_op.f('visit_ibfk_3'), ['patient_name'], unique=False)
        batch_op.create_index(batch_op.f('visit_ibfk_2'), ['doctor_id'], unique=False)
        batch_op.create_index(batch_op.f('visit_ibfk_1'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('national_id_FK'), ['national_id'], unique=False)
        batch_op.create_index(batch_op.f('idx_visit_clinic_id'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('FK_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('FK_age'), ['age'], unique=False)
        batch_op.alter_column('queue_status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               nullable=False,
               comment='Dynamic queue state: waiting | in_progress | completed | paused',
               existing_server_default=sa.text("'waiting'"))
        batch_op.alter_column('actual_end_time',
               existing_type=mysql.DATETIME(),
               comment='Timestamp when doctor clicked Next to END this visit',
               existing_nullable=True)
        batch_op.alter_column('actual_start_time',
               existing_type=mysql.DATETIME(),
               comment='Timestamp when doctor clicked Next to START this visit',
               existing_nullable=True)
        batch_op.alter_column('percentage',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('visit_date',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('clinic_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('national_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=14),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               nullable=True)
        batch_op.alter_column('berth_date',
               existing_type=sa.Date(),
               type_=mysql.YEAR(),
               existing_nullable=False)
        batch_op.alter_column('normalized_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=False)

    with op.batch_alter_table('section', schema=None) as batch_op:
        batch_op.add_column(sa.Column('doctor_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('doctors_name', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('naem_section'), ['name_section'], unique=False)
        batch_op.create_index(batch_op.f('fk_clinic_section'), ['clinic_id'], unique=False)

    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.alter_column('date_performed',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
        batch_op.alter_column('discount',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)

    with op.batch_alter_table('plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discreption', mysql.VARCHAR(collation='utf8mb4_general_ci', length=50), nullable=False))
        batch_op.alter_column('name',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=25),
               existing_nullable=False)

    with op.batch_alter_table('percentages', schema=None) as batch_op:
        batch_op.drop_constraint('_doctor_process_uc', type_='unique')
        batch_op.alter_column('percentage',
               existing_type=mysql.FLOAT(),
               nullable=False)

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('idprocess', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('payment_date_time', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('process_cost', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('cost_process'), 'process', ['process_cost'], ['fee_process'])
        batch_op.create_foreign_key(batch_op.f('idprocess'), 'visit', ['idprocess'], ['process_id'])
        batch_op.create_foreign_key(batch_op.f('patient_id'), 'patient', ['patient_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('discount'), 'visit', ['discount'], ['percentage'])
        batch_op.alter_column('payment_date',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('invoice_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('section_2'), ['section'], unique=False)
        batch_op.create_index(batch_op.f('id_clinic'), ['clinic_id'], unique=False)
        batch_op.create_index(batch_op.f('fk_doctor_id'), ['doctor_id'], unique=False)
        batch_op.alter_column('normalized_name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=255),
               nullable=False)
        batch_op.alter_column('section',
               existing_type=sa.String(length=50),
               type_=mysql.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('gender',
               existing_type=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               nullable=True)
        batch_op.alter_column('berth_date',
               existing_type=sa.Date(),
               type_=mysql.YEAR(),
               existing_nullable=False)
        batch_op.alter_column('national_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=14),
               nullable=False)

    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remaining_amount', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=False))
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=10),
               nullable=False,
               existing_server_default=sa.text("'غير مدفوع'"))
        batch_op.alter_column('discount',
               existing_type=sa.Integer(),
               type_=mysql.FLOAT(),
               existing_nullable=True)
        batch_op.alter_column('invoice_date',
               existing_type=mysql.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('featursplans', schema=None) as batch_op:
        batch_op.alter_column('featur_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('plan_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('featurs', schema=None) as batch_op:
        batch_op.alter_column('discreption',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=80),
               nullable=False)
        batch_op.alter_column('code',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=80),
               existing_nullable=False)

    with op.batch_alter_table('doctor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_queue_position', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_visits_today', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_visits_month', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('doctor_ibfk_1'), ['current_patient'], unique=False)
        batch_op.create_index(batch_op.f('FK_sectionID'), ['section_id'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_general_ci', length=50),
               nullable=True)

    with op.batch_alter_table('consultation_time', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('consultation_time_ibfk_1'), 'doctor', ['doctor_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('consultation_time_ibfk_4'), 'visit', ['current_visit_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(batch_op.f('consultation_time_ibfk_2'), 'clinics', ['clinic_id'], ['clinic_id'], ondelete='CASCADE')
        batch_op.create_foreign_key(batch_op.f('consultation_time_ibfk_3'), 'visit', ['previous_visit_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('idx_doctor_date'), ['doctor_id', 'date_recorded'], unique=False)

    # ### end Alembic commands ###
