"""empty message

Revision ID: 7df14eb3573e
Revises: 
Create Date: 2026-04-11 11:58:18.322974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7df14eb3573e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('berth_date',
               existing_type=mysql.INTEGER(),
               type_=sa.SmallInteger(),
               existing_nullable=True)

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patient', ['patient_phone'], ['phone'])
        batch_op.create_foreign_key(None, 'patient', ['national_id'], ['national_id'])
        batch_op.create_foreign_key(None, 'patient', ['berth_date'], ['berth_date'])
        batch_op.create_foreign_key(None, 'patient', ['status'], ['status'])
        batch_op.create_foreign_key(None, 'section', ['section_id'], ['id'])
        batch_op.create_foreign_key(None, 'patient', ['patient_id'], ['id'])
        batch_op.create_foreign_key(None, 'patient', ['patient_name'], ['name'])
        batch_op.create_foreign_key(None, 'doctor', ['doctor_id'], ['id'])
        batch_op.drop_column('process_cost')
        batch_op.drop_column('visit_date_login')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('visit_date_login', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=False))
        batch_op.add_column(sa.Column('process_cost', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.alter_column('berth_date',
               existing_type=sa.SmallInteger(),
               type_=mysql.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
