"""new edit1

Revision ID: 8015381253f7
Revises: 7df14eb3573e
Create Date: 2026-04-11 13:43:23.192674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8015381253f7'
down_revision = '7df14eb3573e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('visit_ibfk_national_id'), type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('visit_ibfk_national_id'), 'patient', ['national_id'], ['national_id'], onupdate='CASCADE', ondelete='SET NULL')

    # ### end Alembic commands ###
