"""new fix auto increment 

Revision ID: f434c484b74d
Revises: 27b8c558c6a3
Create Date: 2026-04-12 11:15:23.503389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f434c484b74d'
down_revision = '27b8c558c6a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('procedure', schema=None) as batch_op:
        #batch_op.drop_constraint(batch_op.f('VISIT_ID'), type_='foreignkey')
         batch_op.create_foreign_key(None, 'visit', ['visit_id'], ['id'])

    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'patient', ['national_id'], ['national_id'])
        batch_op.create_foreign_key(None, 'patient', ['patient_name'], ['name'])

    # end Alembic commands ###


# def downgrade():
#     pass
    ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visit', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')

    with op.batch_alter_table('procedure', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('VISIT_ID'), 'visit', ['visit_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')

    # end Alembic commands ###
  
